// gentables converts mbelib AMBE codebook headers (ISC) into Go source.
//
//	go run ./tools/gentables -mbelib ../ref/mbelib > mbe/tables_gen.go
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

var (
	reBlock   = regexp.MustCompile(`/\*[\s\S]*?\*/`)
	reLine    = regexp.MustCompile(`//[^\n]*`)
	reDecl    = regexp.MustCompile(`const\s+(float|int)\s+(\w+)\s*\[(\d+)\](?:\s*\[(\d+)\])?\s*=\s*\{([\s\S]*?)\};`)
	reNum     = regexp.MustCompile(`-?\d+(?:\.\d*)?(?:[eE][-+]?\d+)?`)
	wantNames = map[string]bool{}
)

func main() {
	dir := flag.String("mbelib", "../ref/mbelib", "mbelib source directory")
	flag.Parse()
	fmt.Println("// Code generated by tools/gentables from mbelib (ISC licence). DO NOT EDIT.")
	fmt.Println("// Copyright (C) 2010 mbelib Author. See NOTICE.")
	fmt.Println()
	fmt.Println("package mbe")
	for _, f := range []string{"ambe3600x2450_const.h", "ambe3600x2400_const.h"} {
		raw, err := os.ReadFile(filepath.Join(*dir, f))
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		src := reLine.ReplaceAllString(reBlock.ReplaceAllString(string(raw), ""), "")
		for _, m := range reDecl.FindAllStringSubmatch(src, -1) {
			typ, name := m[1], m[2]
			d1, _ := strconv.Atoi(m[3])
			d2 := 1
			if m[4] != "" {
				d2, _ = strconv.Atoi(m[4])
			}
			nums := reNum.FindAllString(m[5], -1)
			if len(nums) != d1*d2 {
				fmt.Fprintf(os.Stderr, "%s: %d values, want %d\n", name, len(nums), d1*d2)
				os.Exit(1)
			}
			gt := "float32"
			if typ == "int" {
				gt = "int8"
			}
			var b strings.Builder
			if m[4] == "" {
				fmt.Fprintf(&b, "\nvar %s = [%d]%s{", name, d1, gt)
				for i, n := range nums {
					if i%8 == 0 {
						b.WriteString("\n\t")
					} else {
						b.WriteString(" ")
					}
					b.WriteString(n + ",")
				}
				b.WriteString("\n}\n")
			} else {
				fmt.Fprintf(&b, "\nvar %s = [%d][%d]%s{\n", name, d1, d2, gt)
				for r := 0; r < d1; r++ {
					b.WriteString("\t{" + strings.Join(nums[r*d2:(r+1)*d2], ", ") + "},\n")
				}
				b.WriteString("}\n")
			}
			fmt.Print(b.String())
		}
	}
}
